apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo1
  name: mongo1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo1
    spec:
      containers:
      - command:
        - /usr/bin/mongod
        - --bind_ip_all
        - --replSet
        - rs0
        image: mongo:4.0-xenial
        name: localmongo1
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /mongo1
          name: mongo1-claim0
      hostname: mongo1
      restartPolicy: Always
      volumes:
      - name: mongo1-claim0
        persistentVolumeClaim:
          claimName: mongo1-claim0
status: {}
