apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo3
  name: mongo3
spec:
  ports:
  - name: "27013"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongo3
status:
  loadBalancer: {}
